backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "news"
    label: "News and Updates"
    folder: "src/pages/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Top Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: AboutUs, name: aboutUs, widget: string}        
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - label: "Eb"
            name: "eb"
            widget: "object"
            fields: 
            - {label: image, name: image, widget: image}
            - {label: text,  name: text, widget: string}
          - label: Comext
            name: comex
            widget: object
            fields: 
            - {label: image, name: image, widget: image}
            - {label: text,  name: text, widget: string}
          - label: JB
            name: jb
            widget: object
            fields: 
            - {label: image, name: image, widget: image}
            - {label: text,  name: text, widget: string}
          - label: bPlus
            name: bPlus
            widget: object
            fields: 
            - {label: image, name: image, widget: image}
            - {label: text,  name: text, widget: string}
          - {label: "Body", name: "html", widget: "markdown"}    
                       
      - file: "src/pages/awards/index.md"
        label: "Awards"
        name: "awards"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "awards-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          
      - file: "src/pages/recommendations/index.md"
        label: "Recommendations"
        name: "recommendations"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "recommendations-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
