# This is a basic workflow that is manually triggered
# ワークフロー名の設定
name: Gatsby build and deploy to a server

# master branch へ push したときにこのワークフローを実行するよう指定
on:
  push:
    branches:
      - master

# 以下，jobs の定義
jobs:
  # 「build」という名前のジョブを定義
  build:
    # ubunts の最新版を指定
    runs-on: ubuntu-latest

    # 実行する処理やコマンドを指定
    steps:
      # レポジトリからの checkout を実行
      - uses: actions/checkout@v3
      # Node のセットアップ
      - name: Use Node.js 19.x
        uses: actions/setup-node@v3
        with:
          node-version: "19.x"
          cache: "yarn"
      # Node の実行（npm install, npm run build）
      - name: Build Project
        run: |
          yarn
          yarn run build
      # 確認のためのリスト表示　必要なければ削除
      - name: List output files
        run: ls -laFG
      # 以下のサイトを参考に github action で build, netlify へ publicフォルダを転送
      # https://github.com/marketplace/actions/netlify-actions
      # V2 に変更，でも Netlify credentials not provided, not deployable と怒られる．．．
      - name: Netlify Actions
        uses: nwtgck/actions-netlify@v2.0.0
        with:
          publish-dir: "./public"
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
      # rsync の設定
      # - name: rsync deployments
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete --exclude="xplore/.htaccess"
          path: public/
          remote_path: ${{ secrets.REMOTE_PATH }}
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.ID_ECDSA_FREEDOM }}
